name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-smoke:
    runs-on: ubuntu-latest

    env:
      PROJECT_DIR: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r "$PROJECT_DIR/requirements.txt"

      - name: Lint
        run: flake8 "$PROJECT_DIR"

      - name: Train (capture metrics)
        run: |
          cd "$PROJECT_DIR"
          python train.py | tee train.log
          RMSE=$(grep -Po 'RMSE:\s*\K[0-9.]+' train.log)
          echo "{\"rmse\": $RMSE, \"branch\": \"${GITHUB_REF_NAME}\"}" > ci-metrics.json

      - name: Unit tests
        run: |
          cd "$PROJECT_DIR"
          pytest -q

      - name: Upload artifacts (model + logs)
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts-${{ github.run_id }}
          path: |
            ${{ env.PROJECT_DIR }}/app/model.joblib
            ${{ env.PROJECT_DIR }}/train.log
            ${{ env.PROJECT_DIR }}/ci-metrics.json
